# This is a basic workflow to help you get started with Actions

name: Coverage

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Coverage Check
      run: |
        pip install pytest
        pytest --cov=friendly_ground_truth ./tests --cov-branch --cov-report=xml
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v2.0.2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
